openapi: 3.0.0
x-stoplight:
  id: utvd8kedry3sp
info:
  title: Coffee Review API
  version: '1.0'
  description: |-
    This API allows you to create a user profile where you can write reviews of different coffees that you have tried.
    For now the brands and products are from the swedish selection.
servers:
  - url: 'http://localhost:5000'
paths:
  /coffee:
    get:
      summary: Your GET endpoint
      tags:
        - Standard usage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/coffees_reponse'
              examples: {}
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-coffee
      description: Returns all the coffee in API endpoint.
  /coffee/reviews:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-coffee-reviews
      description: Get all coffee reviews.
  /coffee/search:
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/coffees_reponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-coffee-search
      tags:
        - Standard usage
      description: 'Search for a coffee product using a search_word parameter. Returns results of the search, zero or more coffee objects.'
      parameters:
        - schema:
            type: string
          in: query
          name: search_word
          description: Can be full or part of searched string.
  '/coffee/{coffee_id}':
    parameters:
      - schema:
          type: string
        name: coffee_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - Standard usage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/coffees_reponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
      operationId: get-coffee-coffee_id
      description: 'Returns information about coffee object with id: ''coffee_id''.'
    post:
      summary: ''
      operationId: post-coffee-coffee_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review_response'
              examples:
                Example 1:
                  value:
                    reviews:
                      - id: 0
                        user_id: 0
                        coffee_id: string
                        review: string
                        time_stamp: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
        '500':
          description: Internal Server Error
      description: 'Post a new review for coffee product with id: ''coffee_id''. Needs to be an authorized user to post a review.'
      tags:
        - Authorized usage
      parameters:
        - schema:
            type: string
          in: header
          name: authentication
          description: Authentication token received from registering.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review_post'
            examples: {}
        description: Review body to add a coffee review to the database.
  '/coffee/{coffee_id}/reviews':
    parameters:
      - schema:
          type: string
        name: coffee_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - Standard usage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review_response'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIClientError'
        '500':
          description: Internal Server Error
      operationId: get-coffee-coffee_id-reviews
      description: Get all reviews connected to a specific coffee id.
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: ''
      operationId: get-users-userId
      responses:
        '200':
          description: OK
      description: Returns information about a specific user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              Example 1:
                value:
                  id: 32
                  name: Allan Wood
                  regTime: '2019-08-24'
  /users/register:
    post:
      summary: Create New User
      operationId: post-users-register
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
              examples:
                Example 1:
                  value:
                    token: uaRkfY&kand#kaS==
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content: {}
        description: Post the necessary fields for the API to create a new user.
      description: Register a new user and recieve a personal token for authorization.
      parameters:
        - schema:
            type: string
          in: query
          name: name
          description: First and last name of user.
        - schema:
            type: string
          in: query
          name: email
          description: email address of the user.
    parameters: []
  /users:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-users
      description: Get all registered users.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Token for authorization.
components:
  schemas:
    User:
      title: User
      type: object
      x-examples:
        Example 1:
          id: 32
          name: Allan Wood
          regTime: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        name:
          type: string
          x-stoplight:
            id: huecktyltfwwm
        regTime:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: e350m60vvidkb
      required:
        - id
        - name
      description: Non-sensitive user information.
    Token:
      title: Token
      x-stoplight:
        id: 5rdl6ctwiiomk
      type: object
      properties:
        token:
          type: string
          x-stoplight:
            id: k3s1c4brkdp67
      x-examples:
        Example 1:
          token: uaRkfY&kand#kaS==
    coffee:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        url:
          type: string
      x-examples:
        Example 1:
          id: '7310731101611'
          name: ZOÉGAS Hazienda - 450 G
          url: 'https://www.dittsvenskaskafferi.se/zogas-hazienda-450g-7310731101611'
      title: ''
      description: Coffee object in JSON database.
    coffees_reponse:
      type: object
      x-examples:
        Example 1:
          coffee:
            - id: '7310731101611'
              name: ZOÉGAS Hazienda - 450 G
              url: 'https://www.dittsvenskaskafferi.se/zogas-hazienda-450g-7310731101611'
            - id: '7310731101888'
              name: ZOÉGAS Västkust - 450 G
              url: 'https://www.dittsvenskaskafferi.se/zogas-vstkust-450g-7310731101888'
            - id: '7310731102397'
              name: ZOÉGAS KAHAWA - 450G
              url: 'https://www.dittsvenskaskafferi.se/zogas-kahawa-450g-7310731102397'
      properties:
        coffee:
          type: array
          items:
            $ref: '#/components/schemas/coffee'
      description: Dictionary structure of coffee objsects returned from JSON database.
    APIClientError:
      title: APIClientError
      x-stoplight:
        id: 677it1bo9d2bu
      type: object
      x-examples:
        Example 1:
          error: Missing required parameters.
      description: Client error response with message of the error.
      properties:
        error:
          type: string
          x-stoplight:
            id: 3c6uh7y205c3b
      required:
        - error
    Review_post:
      title: Review_post
      x-stoplight:
        id: i94ymw5f8qhtq
      type: object
      description: Structure of review body when posting a new review.
      properties:
        review:
          type: string
          x-stoplight:
            id: 0kylrqxqg8x2z
      x-examples:
        Example 1:
          review: Tasteful!
    Review_response:
      type: object
      x-stoplight:
        id: 51zia3ngj2iaq
      x-examples:
        Example 1:
          reviews:
            - coffee_id: 7310731101611
              id: 12
              review: Smakrik
              time_stamp: '2023-05-04 20:11:54'
              user_id: 4
            - coffee_id: 7310731101611
              id: 13
              review: Smakrik
              time_stamp: '2023-05-04 20:36:49'
              user_id: 4
      properties:
        reviews:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              user_id:
                type: integer
              coffee_id:
                type: string
              review:
                type: string
              time_stamp:
                type: string
      description: Response structure of reviews returned on get request.
      title: Review response
